# DOC_LINK: DOC-CONFIG-DIR-MANIFEST-RUNTIME-EVENTS-1026
classification: runtime
dir_id: DIR-ALL_AI-RUNTIME-EVENTS-12df6f69
doc_id: DOC-CONFIG-DIR-MANIFEST-RUNTIME-EVENTS-1026
files:
  documentation:
  - README.md
  metadata:
  - DIR_MANIFEST.yaml
  - .dir_id
  registries:
  - EVENT_REGISTRY.yaml
meta: {}
ownership:
  created: '2026-01-04T01:30:08.381791Z'
  owner: Event System
  status: active
purpose: Registry for Event Identifier (event_id)
version: 1.0.0
