# DOC_LINK: DOC-CONFIG-DIR-MANIFEST-RUNTIME-CORRELATION-1021
classification: runtime
dir_id: DIR-ALL_AI-RUNTIME-CORRELATION-bfb2ae03
doc_id: DOC-CONFIG-DIR-MANIFEST-RUNTIME-CORRELATION-1021
files:
  documentation:
  - README.md
  metadata:
  - DIR_MANIFEST.yaml
  - .dir_id
  registries:
  - CORR_REGISTRY.yaml
meta: {}
ownership:
  created: '2026-01-04T01:29:36.224799Z'
  owner: Observability
  status: active
purpose: Registry for Correlation Identifier (correlation_id)
version: 1.0.0
