# DOC_LINK: DOC-CONFIG-DIR-MANIFEST-RUNTIME-GRAPH-1027
classification: derived
dir_id: DIR-ALL_AI-RUNTIME-GRAPH-ed46b355
doc_id: DOC-CONFIG-DIR-MANIFEST-RUNTIME-GRAPH-1027
files:
  documentation:
  - README.md
  metadata:
  - DIR_MANIFEST.yaml
  - .dir_id
  registries:
  - EDGE_REGISTRY.yaml
meta: {}
ownership:
  created: '2026-01-04T01:29:35.427637Z'
  owner: Graph System
  status: active
purpose: Registry for Graph Edge Identifier (graph_edge_id)
version: 1.0.0
