# DOC_LINK: DOC-CONFIG-DIR-MANIFEST-GOVERNANCE-POLICIES-1010
classification: minted
dir_id: DIR-ALL_AI-GOVERNANCE-POLICIES-99fda87d
doc_id: DOC-CONFIG-DIR-MANIFEST-GOVERNANCE-POLICIES-1010
files:
  documentation:
  - README.md
  - USAGE.md
  - RUNBOOK.md
  metadata:
  - DIR_MANIFEST.yaml
  - .dir_id
  policies:
  - definition_of_done.yaml
  - work_id_policy.md
  registries:
  - POLICY_REGISTRY.yaml
meta: {}
ownership:
  created: '2026-01-04T01:30:27.209366Z'
  owner: Governance Team
  status: active
  updated: '2026-01-04T02:16:00.000000Z'
purpose: Registry for Policy Identifier (policy_id)
version: 1.0.1
