# DOC_LINK: DOC-CONFIG-DIR-MANIFEST-RUNTIME-METRICS-1029
classification: minted
dir_id: DIR-ALL_AI-RUNTIME-METRICS-9f162b96
doc_id: DOC-CONFIG-DIR-MANIFEST-RUNTIME-METRICS-1029
files:
  documentation:
  - README.md
  metadata:
  - DIR_MANIFEST.yaml
  - .dir_id
  registries:
  - METRIC_REGISTRY.yaml
meta: {}
ownership:
  created: '2026-01-04T01:30:10.231766Z'
  owner: Metrics System
  status: active
purpose: Registry for Metric Identifier (metric_id)
version: 1.0.0
