# DOC_LINK: DOC-CONFIG-DIR-MANIFEST-RUNTIME-ERRORS-1024
classification: minted
dir_id: DIR-ALL_AI-RUNTIME-ERRORS-762d7c24
doc_id: DOC-CONFIG-DIR-MANIFEST-RUNTIME-ERRORS-1024
files:
  documentation:
  - README.md
  metadata:
  - DIR_MANIFEST.yaml
  - .dir_id
  registries:
  - ERROR_REGISTRY.yaml
meta: {}
ownership:
  created: '2026-01-04T01:29:05.434427Z'
  owner: Error Taxonomy
  status: active
purpose: Registry for Error Code Identifier (error_code)
version: 1.0.0
