# DOC_LINK: DOC-CONFIG-DIR-MANIFEST-RUNTIME-SYMBOLS-1036
classification: derived
dir_id: DIR-ALL_AI-RUNTIME-SYMBOLS-52db3b92
doc_id: DOC-CONFIG-DIR-MANIFEST-RUNTIME-SYMBOLS-1036
files:
  documentation:
  - README.md
  metadata:
  - DIR_MANIFEST.yaml
  - .dir_id
  registries:
  - SYMBOL_REGISTRY.yaml
meta: {}
ownership:
  created: '2026-01-04T01:29:57.857910Z'
  owner: Code Analysis
  status: active
purpose: Registry for Code Symbol Identifier (symbol_id)
version: 1.0.0
