# DOC_LINK: DOC-REGISTRY-ENVIRONMENT-ID-001
doc_id: DOC-REGISTRY-ENVIRONMENT-ID-001
meta:
  version: 1.0.0
  created_utc: '2026-01-04T01:30:32.180290Z'
  updated_utc: '2026-01-04T01:30:32.180290Z'
  total_entries: 0
  owner: Environment Management
  description: Identifier for deployment environments
environment_ids: []
