# DOC_LINK: DOC-REGISTRY-CONFIG-ID-001
doc_id: DOC-REGISTRY-CONFIG-ID-001
meta:
  version: 1.0.0
  created_utc: '2026-01-04T01:29:23.241279Z'
  updated_utc: '2026-01-04T01:29:23.241279Z'
  total_entries: 0
  owner: Configuration Management
  description: Identifier for configuration items
config_ids: []
categories:
  DEV:
    description: DEV category
  TEST:
    description: TEST category
  STAGE:
    description: STAGE category
  PROD:
    description: PROD category
