#!/usr/bin/env python3
"""Review technical documentation for completeness and accuracy."""

import sys
from pathlib import Path
from datetime import datetime


REQUIRED_DOCS = [
    {'path': 'README.md', 'category': 'Overview'},
    {'path': 'docs/api_reference.md', 'category': 'API Documentation'},
    {'path': 'docs/runbooks', 'category': 'Operational Runbooks'},
    {'path': 'schemas', 'category': 'Schema Documentation'},
    {'path': 'PHASE_0_TO_5_COMPLETE.md', 'category': 'Migration Guide'}
]


def review_documentation(output_path):
    """Review documentation and generate report."""
    report_lines = [
        "# Documentation Review Report\n",
        f"**Generated:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}\n",
        "\n---\n\n",
        "## Documentation Review\n\n"
    ]
    
    found_count = 0
    missing_count = 0
    
    report_lines.append("### Required Documentation\n\n")
    report_lines.append("| Document | Category | Status |\n")
    report_lines.append("|----------|----------|--------|\n")
    
    for doc in REQUIRED_DOCS:
        doc_path = Path(doc['path'])
        if doc_path.exists():
            status = "✓ Present"
            found_count += 1
        else:
            status = "✗ Missing"
            missing_count += 1
        
        report_lines.append(f"| {doc['path']} | {doc['category']} | {status} |\n")
    
    report_lines.append("\n### Summary\n\n")
    report_lines.append(f"- **Total Required:** {len(REQUIRED_DOCS)}\n")
    report_lines.append(f"- **Present:** {found_count}\n")
    report_lines.append(f"- **Missing:** {missing_count}\n")
    report_lines.append(f"- **Completion Rate:** {(found_count/len(REQUIRED_DOCS)*100):.1f}%\n\n")
    
    if missing_count == 0:
        report_lines.append("### Status: ✓ COMPLETE\n\n")
        report_lines.append("All required documentation is present.\n")
    else:
        report_lines.append("### Status: ⚠ INCOMPLETE\n\n")
        report_lines.append(f"{missing_count} required document(s) missing.\n")
    
    report_lines.append("\n---\n\n")
    report_lines.append("## Recommendations\n\n")
    
    if missing_count > 0:
        report_lines.append("### Missing Documentation\n\n")
        for doc in REQUIRED_DOCS:
            if not Path(doc['path']).exists():
                report_lines.append(f"- Create {doc['path']} ({doc['category']})\n")
    else:
        report_lines.append("- All documentation complete\n")
        report_lines.append("- Consider adding user guides for end users\n")
        report_lines.append("- Schedule quarterly documentation review\n")
    
    report_lines.append("\n---\n")
    report_lines.append("*Report generated by review_documentation.py*\n")
    
    # Write report
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    with open(output, 'w', encoding='utf-8') as f:
        f.writelines(report_lines)
    
    print(f"Documentation review complete: {output_path}")
    print(f"Completion Rate: {(found_count/len(REQUIRED_DOCS)*100):.1f}%")
    
    return 0 if missing_count == 0 else 1


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Usage: python review_documentation.py --output <report.md>")
        sys.exit(1)
    
    output_path = None
    
    for i, arg in enumerate(sys.argv):
        if arg == '--output' and i + 1 < len(sys.argv):
            output_path = sys.argv[i + 1]
    
    if not output_path:
        print("Error: --output is required")
        sys.exit(1)
    
    sys.exit(review_documentation(output_path))
