# DOC_LINK: DOC-CONFIG-DIR-MANIFEST-RUNTIME-DEPLOYMENTS-1023
classification: runtime
dir_id: DIR-ALL_AI-RUNTIME-DEPLOYMENTS-8a5acbe6
doc_id: DOC-CONFIG-DIR-MANIFEST-RUNTIME-DEPLOYMENTS-1023
files:
  documentation:
  - README.md
  metadata:
  - DIR_MANIFEST.yaml
  - .dir_id
  registries:
  - DEPLOY_REGISTRY.yaml
meta: {}
ownership:
  created: '2026-01-04T01:30:31.310569Z'
  owner: Deployment System
  status: active
purpose: Registry for Deployment Identifier (deployment_id)
version: 1.0.0
