# DOC_LINK: DOC-CONFIG-DIR-MANIFEST-RUNTIME-PIPELINES-1032
classification: runtime
dir_id: DIR-ALL_AI-RUNTIME-PIPELINES-905b6d04
doc_id: DOC-CONFIG-DIR-MANIFEST-RUNTIME-PIPELINES-1032
files:
  documentation:
  - README.md
  metadata:
  - DIR_MANIFEST.yaml
  - .dir_id
  registries:
  - PIPELINE_REGISTRY.yaml
meta: {}
ownership:
  created: '2026-01-04T01:29:22.397247Z'
  owner: Pipeline Execution
  status: active
purpose: Registry for Pipeline Instance Identifier (pipeline_id)
version: 1.0.0
