#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Combines all section JSON and Markdown files into unified versions.

.DESCRIPTION
    This script combines all sec_*.json files into UNIFIED_ALL_SECTIONS.json
    and all sec_*.inst.md files into UNIFIED_ALL_INSTRUCTIONS.md.
    Run on-demand to capture the latest versions of all files.

.EXAMPLE
    .\combine_sections.ps1
    
.NOTES
    Created: 2026-01-28
    Location: C:\Users\richg\Gov_Reg\sections\
#>

param(
    [string]$SectionsDir = "C:\Users\richg\Gov_Reg\sections",
    [switch]$Verbose
)

$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "═══════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  SECTION FILE COMBINER" -ForegroundColor Cyan
Write-Host "═══════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""
Write-Host "Timestamp: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')" -ForegroundColor Gray
Write-Host "Directory: $SectionsDir" -ForegroundColor Gray
Write-Host ""

# ============================================================================
# STEP 1: Combine JSON Files
# ============================================================================
Write-Host "📦 COMBINING JSON FILES" -ForegroundColor Yellow
Write-Host "───────────────────────────────────────────────────────────" -ForegroundColor Gray

$jsonFiles = Get-ChildItem "$SectionsDir\sec_*.json" | Sort-Object Name

if ($jsonFiles.Count -eq 0) {
    Write-Host "✗ No JSON files found matching sec_*.json" -ForegroundColor Red
    exit 1
}

$combinedJson = [ordered]@{
    unified_master_template = [ordered]@{
        version = "1.0"
        generated_at = (Get-Date -Format "yyyy-MM-ddTHH:mm:ss.fffZ")
        total_sections = $jsonFiles.Count
        source_directory = $SectionsDir
        sections = @()
    }
}

foreach ($file in $jsonFiles) {
    try {
        $content = Get-Content $file.FullName -Raw -Encoding UTF8 | ConvertFrom-Json
        $combinedJson.unified_master_template.sections += $content
        
        if ($Verbose) {
            Write-Host "  ✓ $($file.Name)" -ForegroundColor Green
        } else {
            Write-Host "  ✓ $($file.Name)" -ForegroundColor Green -NoNewline
            Write-Host ""
        }
    }
    catch {
        Write-Host "  ✗ Failed to parse: $($file.Name)" -ForegroundColor Red
        Write-Host "    Error: $($_.Exception.Message)" -ForegroundColor Red
        exit 1
    }
}

$outputJsonPath = Join-Path $SectionsDir "UNIFIED_ALL_SECTIONS.json"
$combinedJson | ConvertTo-Json -Depth 100 | Set-Content $outputJsonPath -Encoding UTF8

$jsonSize = [math]::Round((Get-Item $outputJsonPath).Length / 1KB, 2)
Write-Host ""
Write-Host "✓ Created: UNIFIED_ALL_SECTIONS.json" -ForegroundColor Green
Write-Host "  Sections: $($jsonFiles.Count)" -ForegroundColor White
Write-Host "  Size: $jsonSize KB" -ForegroundColor White

# ============================================================================
# STEP 2: Combine Markdown Files
# ============================================================================
Write-Host ""
Write-Host "📝 COMBINING MARKDOWN FILES" -ForegroundColor Yellow
Write-Host "───────────────────────────────────────────────────────────" -ForegroundColor Gray

$mdFiles = Get-ChildItem "$SectionsDir\sec_*.inst.md" | Sort-Object Name

if ($mdFiles.Count -eq 0) {
    Write-Host "✗ No Markdown files found matching sec_*.inst.md" -ForegroundColor Red
    exit 1
}

$combinedMd = @()

# Add header
$combinedMd += "# UNIFIED MASTER TEMPLATE - ALL INSTRUCTIONS"
$combinedMd += ""
$combinedMd += "**Version:** 1.0"
$combinedMd += "**Generated:** $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
$combinedMd += "**Total Sections:** $($mdFiles.Count)"
$combinedMd += "**Source Directory:** ``$SectionsDir``"
$combinedMd += ""
$combinedMd += "> **Note:** This file is auto-generated by ``combine_sections.ps1``. Do not edit directly."
$combinedMd += "> Edit individual ``sec_*.inst.md`` files and re-run the script."
$combinedMd += ""
$combinedMd += "---"
$combinedMd += ""

# Add table of contents
$combinedMd += "## Table of Contents"
$combinedMd += ""
$sectionNum = 0
foreach ($file in $mdFiles) {
    $firstLine = (Get-Content $file.FullName -TotalCount 1).Trim()
    # Remove leading # from title
    $title = $firstLine -replace '^#+\s*', ''
    $combinedMd += "$($sectionNum + 1). [$title](#section-$sectionNum)"
    $sectionNum++
}
$combinedMd += ""
$combinedMd += "---"
$combinedMd += ""
$combinedMd += ""

# Add each section with separator
$sectionNum = 0
foreach ($file in $mdFiles) {
    $content = Get-Content $file.FullName -Raw -Encoding UTF8
    
    $combinedMd += "<a name=`"section-$sectionNum`"></a>"
    $combinedMd += ""
    $combinedMd += $content
    $combinedMd += ""
    $combinedMd += ""
    $combinedMd += "---"
    $combinedMd += ""
    $combinedMd += ""
    
    if ($Verbose) {
        Write-Host "  ✓ $($file.Name)" -ForegroundColor Green
    } else {
        Write-Host "  ✓ $($file.Name)" -ForegroundColor Green -NoNewline
        Write-Host ""
    }
    $sectionNum++
}

$outputMdPath = Join-Path $SectionsDir "UNIFIED_ALL_INSTRUCTIONS.md"
$combinedMd -join "`n" | Set-Content $outputMdPath -Encoding UTF8

$mdSize = [math]::Round((Get-Item $outputMdPath).Length / 1KB, 2)
$mdLines = (Get-Content $outputMdPath).Count

Write-Host ""
Write-Host "✓ Created: UNIFIED_ALL_INSTRUCTIONS.md" -ForegroundColor Green
Write-Host "  Sections: $($mdFiles.Count)" -ForegroundColor White
Write-Host "  Size: $mdSize KB" -ForegroundColor White
Write-Host "  Lines: $mdLines" -ForegroundColor White

# ============================================================================
# Summary
# ============================================================================
Write-Host ""
Write-Host "═══════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  ✓ COMBINATION COMPLETE" -ForegroundColor Green
Write-Host "═══════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""
Write-Host "Output files created in:" -ForegroundColor White
Write-Host "  $SectionsDir" -ForegroundColor Gray
Write-Host ""
Write-Host "  📄 UNIFIED_ALL_SECTIONS.json ($jsonSize KB)" -ForegroundColor Yellow
Write-Host "  📄 UNIFIED_ALL_INSTRUCTIONS.md ($mdSize KB, $mdLines lines)" -ForegroundColor Yellow
Write-Host ""
Write-Host "Next steps:" -ForegroundColor White
Write-Host "  - Review unified files for completeness" -ForegroundColor Gray
Write-Host "  - Re-run this script anytime to capture latest changes" -ForegroundColor Gray
Write-Host ""
