# DOC_LINK: DOC-CONFIG-DIR-MANIFEST-RUNTIME-ALERTS-1019
classification: minted
dir_id: DIR-ALL_AI-RUNTIME-ALERTS-de1e69c6
doc_id: DOC-CONFIG-DIR-MANIFEST-RUNTIME-ALERTS-1019
files:
  documentation:
  - README.md
  metadata:
  - DIR_MANIFEST.yaml
  - .dir_id
  registries:
  - ALERT_REGISTRY.yaml
meta: {}
ownership:
  created: '2026-01-04T01:30:09.176675Z'
  owner: Monitoring
  status: active
purpose: Registry for Alert Rule Identifier (alert_id)
version: 1.0.0
