# DOC_LINK: DOC-CONFIG-DIR-MANIFEST-RUNTIME-CALLSITES-1020
classification: derived
dir_id: DIR-ALL_AI-RUNTIME-CALLSITES-84ebe534
doc_id: DOC-CONFIG-DIR-MANIFEST-RUNTIME-CALLSITES-1020
files:
  documentation:
  - README.md
  metadata:
  - DIR_MANIFEST.yaml
  - .dir_id
  registries:
  - CALLSITE_REGISTRY.yaml
meta: {}
ownership:
  created: '2026-01-04T01:29:59.538143Z'
  owner: Static Analysis
  status: active
purpose: Registry for Call Site Identifier (callsite_id)
version: 1.0.0
