# DOC_LINK: DOC-CONFIG-DIR-MANIFEST-RUNTIME-TRACES-1037
classification: runtime
dir_id: DIR-ALL_AI-RUNTIME-TRACES-d66bdfef
doc_id: DOC-CONFIG-DIR-MANIFEST-RUNTIME-TRACES-1037
files:
  documentation:
  - README.md
  metadata:
  - DIR_MANIFEST.yaml
  - .dir_id
  registries:
  - TRACE_REGISTRY.yaml
meta: {}
ownership:
  created: '2026-01-04T01:29:07.065472Z'
  owner: Observability
  status: active
purpose: Registry for Trace Identifier (trace_id)
version: 1.0.0
