#!/usr/bin/env python3
"""
E2E Documentation Generator
Generates comprehensive documentation from unified schema and master index.

Outputs:
1. Markdown documentation (README, phase guides, workflows, references)
2. Mermaid diagrams (state machines, workflows, component interactions)
3. DrawIO XML files (visual process maps with swimlanes)
4. HTML interactive view (searchable, filterable catalog)

Usage:
    python pfa_generate_e2e_docs.py --schema unified.yaml --index master_index.json --output-dir docs/e2e/ --formats markdown mermaid drawio html
"""
DOC_ID: DOC-SCRIPT-TOOLS-PFA-GENERATE-E2E-DOCS-949

import json
import yaml
import argparse
from pathlib import Path
from typing import Dict, List, Any, Optional
from collections import defaultdict
import sys

class E2EDocGenerator:
    """Generates multi-format documentation from unified schema and master index"""

    def __init__(self, schema_path: Path, index_path: Path, output_dir: Path):
        self.schema_path = schema_path
        self.index_path = index_path
        self.output_dir = output_dir

        # Load data
        self.schema = self._load_yaml(schema_path)
        self.index = self._load_json(index_path)

        # Extract metadata
        self.meta = self.schema.get('meta', {})
        self.steps = self.schema.get('steps', [])
        self.universal_phases = self.schema.get('universal_phases', [])

        print(f"Loaded schema: {self.meta.get('schema_id', 'Unknown')}")
        print(f"  Version: {self.meta.get('version', 'Unknown')}")
        print(f"  Steps: {len(self.steps)}")
        print(f"  Phases: {len(self.universal_phases)}")

    def _load_yaml(self, path: Path) -> Dict:
        """Load YAML file"""
        with open(path, 'r', encoding='utf-8') as f:
            return yaml.safe_load(f)

    def _load_json(self, path: Path) -> Dict:
        """Load JSON file"""
        with open(path, 'r', encoding='utf-8') as f:
            return json.load(f)

    def _save_file(self, path: Path, content: str):
        """Save file with directory creation"""
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"  ✓ Generated: {path.relative_to(self.output_dir)}")

    # ============================================================================
    # MARKDOWN GENERATION
    # ============================================================================

    def generate_markdown(self):
        """Generate all markdown documentation"""
        print("\n=== Generating Markdown Documentation ===\n")

        # Main README
        self._generate_readme()

        # Phase guides (9 files)
        self._generate_phase_guides()

        # Component reference
        self._generate_component_reference()

        # Operations reference
        self._generate_operations_reference()

        # Workflow guides (5+ files)
        self._generate_workflow_guides()

        # Phase mappings reference
        self._generate_phase_mappings()

    def _generate_readme(self):
        """Generate main README.md"""
        readme = f"""# E2E Process Map Documentation

**Schema:** {self.meta.get('schema_id', 'Unknown')}
**Version:** {self.meta.get('version', 'Unknown')}
**Generated:** {self.meta.get('last_updated', 'Unknown')}

---

## Overview

This documentation covers the complete end-to-end process map with **{len(self.steps)} steps** across **{len(self.universal_phases)} universal phases**.

### Source Schemas

{self._format_list(self.meta.get('source_schemas', []))}

### Merge Statistics

- **Total steps merged:** {self.meta.get('merge_statistics', {}).get('total_steps_merged', 'Unknown')}
- **Unique steps after dedup:** {self.meta.get('merge_statistics', {}).get('unique_steps_after_dedup', 'Unknown')}
- **Duplicates removed:** {self.meta.get('merge_statistics', {}).get('duplicates_removed', 'Unknown')}

---

## Universal Phases

{self._generate_phase_tree()}

---

## Navigation

### By Phase
{self._generate_phase_links()}

### By Component
- [Component Reference](components.md) - All {len(self.index.get('by_component', {}))} components

### By Operation
- [Operations Reference](operations.md) - All {len(self.index.get('by_operation', {}))} operation types

### By Workflow
{self._generate_workflow_links()}

---

## Statistics

- **Total Steps:** {len(self.steps)}
- **Phases:** {len(self.universal_phases)}
- **Components:** {len(self.index.get('by_component', {}))}
- **Operations:** {len(self.index.get('by_operation', {}))}
- **Workflows:** {len(self.index.get('by_workflow', {}))}

---

## Quick Links

- [Phase State Machine Diagram](diagrams/phase_state_machine.md)
- [Full E2E Workflow](workflows/full_e2e.md)
- [Component Interactions](diagrams/component_interactions.md)

---

**Generated by:** pfa_generate_e2e_docs.py
"""
        self._save_file(self.output_dir / "README.md", readme)

    def _generate_phase_tree(self) -> str:
        """Generate phase tree with step counts"""
        tree = []
        phase_index = self.index.get('by_phase', {})

        for phase_id in self.universal_phases:
            # Phase is just a string ID, not an object
            step_count = len(phase_index.get(phase_id, []))
            phase_name = phase_id.replace('_', ' ').title()

            tree.append(f"### {phase_name} ({step_count} steps)")
            tree.append(f"**Phase ID:** `{phase_id}`")
            tree.append("")

        return "\n".join(tree)

    def _generate_phase_links(self) -> str:
        """Generate links to phase guides"""
        links = []
        for phase_id in self.universal_phases:
            phase_name = phase_id.replace('_', ' ').title()
            links.append(f"- [{phase_name}](phases/{phase_id}.md)")
        return "\n".join(links)

    def _generate_workflow_links(self) -> str:
        """Generate links to workflow guides"""
        links = []
        workflows = self.index.get('by_workflow', {})
        for workflow_name in workflows.keys():
            links.append(f"- [{workflow_name.replace('_', ' ').title()}](workflows/{workflow_name}.md)")
        return "\n".join(links)

    def _format_list(self, items: List[str]) -> str:
        """Format list of items as markdown list"""
        return "\n".join(f"- {item}" for item in items)

    def _generate_phase_guides(self):
        """Generate individual phase guide files"""
        phases_dir = self.output_dir / "phases"
        phase_index = self.index.get('by_phase', {})

        for phase_id in self.universal_phases:
            phase_name = phase_id.replace('_', ' ').title()
            step_ids = phase_index.get(phase_id, [])
            steps = [s for s in self.steps if s.get('step_id') in step_ids]

            guide = f"""# {phase_name}

**Phase ID:** `{phase_id}`
**Steps:** {len(steps)}

---

## Overview

This phase contains {len(steps)} steps that handle {phase_name.lower()} activities.

---

## Steps in this Phase

{self._generate_step_table(steps)}

---

## Dependencies

{self._generate_phase_dependencies(phase_id)}

---

**Navigation:** [← Back to Index](../README.md) | [Next Phase →](../phases/{self._get_next_phase_id(phase_id)}.md)
"""
            self._save_file(phases_dir / f"{phase_id}.md", guide)

    def _generate_step_table(self, steps: List[Dict]) -> str:
        """Generate markdown table of steps"""
        if not steps:
            return "*No steps in this phase*"

        table = ["| Step ID | Name | Component | Operation |",
                 "|---------|------|-----------|-----------|"]

        for step in steps[:10]:  # Limit to first 10 for brevity
            step_id = step.get('step_id', 'Unknown')
            name = step.get('name', 'Unknown')[:40]
            component = step.get('responsible_component', 'Unknown')[:30]
            operation = step.get('operation_kind', 'Unknown')
            table.append(f"| {step_id} | {name} | {component} | {operation} |")

        if len(steps) > 10:
            table.append(f"| ... | *{len(steps) - 10} more steps* | ... | ... |")

        return "\n".join(table)



    def _generate_phase_dependencies(self, phase_id: str) -> str:
        """Generate phase dependency information"""
        # Simplified - could be enhanced with actual dependency analysis
        return "*Phase dependencies to be analyzed*"

    def _get_next_phase_id(self, current_phase_id: str) -> str:
        """Get next phase ID in sequence"""
        try:
            idx = self.universal_phases.index(current_phase_id)
            return self.universal_phases[idx + 1] if idx + 1 < len(self.universal_phases) else self.universal_phases[0]
        except ValueError:
            return self.universal_phases[0] if self.universal_phases else 'unknown'

    def _generate_component_reference(self):
        """Generate component reference documentation"""
        components = self.index.get('by_component', {})

        content = f"""# Component Reference

**Total Components:** {len(components)}

---

## Component Index

{self._generate_component_index(components)}

---

## Component Details

{self._generate_component_details(components)}
"""
        self._save_file(self.output_dir / "components.md", content)

    def _generate_component_index(self, components: Dict) -> str:
        """Generate component index"""
        index = []
        for component_name in sorted(components.keys()):
            step_count = len(components[component_name])
            index.append(f"- [{component_name}](#{component_name.replace('::', '-')}) - {step_count} steps")
        return "\n".join(index)

    def _generate_component_details(self, components: Dict) -> str:
        """Generate detailed component information"""
        details = []
        for component_name in sorted(components.keys()):
            step_ids = components[component_name]
            steps = [s for s in self.steps if s.get('step_id') in step_ids]

            details.append(f"### {component_name}")
            details.append(f"**Steps:** {len(steps)}")
            details.append("")
            details.append(self._generate_step_table(steps))
            details.append("")

        return "\n".join(details)

    def _generate_operations_reference(self):
        """Generate operations reference documentation"""
        operations = self.index.get('by_operation', {})

        content = f"""# Operations Reference

**Total Operation Types:** {len(operations)}

---

## Operation Index

{self._generate_operation_index(operations)}

---

## Operation Details

{self._generate_operation_details(operations)}
"""
        self._save_file(self.output_dir / "operations.md", content)

    def _generate_operation_index(self, operations: Dict) -> str:
        """Generate operation index"""
        index = []
        for operation in sorted(operations.keys()):
            step_count = len(operations[operation])
            index.append(f"- [{operation}](#{operation.replace('_', '-')}) - {step_count} steps")
        return "\n".join(index)

    def _generate_operation_details(self, operations: Dict) -> str:
        """Generate detailed operation information"""
        details = []
        for operation in sorted(operations.keys()):
            step_ids = operations[operation]

            details.append(f"### {operation}")
            details.append(f"**Steps using this operation:** {len(step_ids)}")
            details.append(f"**Step IDs:** {', '.join(step_ids[:5])}")
            if len(step_ids) > 5:
                details.append(f"... and {len(step_ids) - 5} more")
            details.append("")

        return "\n".join(details)

    def _generate_workflow_guides(self):
        """Generate workflow guide files"""
        workflows_dir = self.output_dir / "workflows"
        workflows = self.index.get('by_workflow', {})

        for workflow_name, step_ids in workflows.items():
            steps = [s for s in self.steps if s.get('step_id') in step_ids]

            guide = f"""# {workflow_name.replace('_', ' ').title()} Workflow

**Workflow ID:** {workflow_name}
**Steps:** {len(steps)}

---

## Workflow Overview

*Workflow description to be added*

---

## Workflow Steps

{self._generate_workflow_step_list(steps)}

---

## Workflow Diagram

See [workflow diagram](../diagrams/workflow_{workflow_name}.md) for visual representation.

---

**Navigation:** [← Back to Index](../README.md)
"""
            self._save_file(workflows_dir / f"{workflow_name}.md", guide)

    def _generate_workflow_step_list(self, steps: List[Dict]) -> str:
        """Generate numbered list of workflow steps"""
        if not steps:
            return "*No steps in this workflow*"

        step_list = []
        for i, step in enumerate(steps, 1):
            step_id = step.get('step_id', 'Unknown')
            name = step.get('name', 'Unknown')
            step_list.append(f"{i}. **{step_id}** - {name}")

        return "\n".join(step_list)

    def _generate_phase_mappings(self):
        """Generate phase mappings reference"""
        content = """# Phase Mappings Reference

**Original Phases → Universal Phases**

This document shows how original phase names from source schemas map to the 9 universal phases.

---

## Mapping Table

*Phase mappings to be extracted from schema*

---

**Navigation:** [← Back to Index](README.md)
"""
        self._save_file(self.output_dir / "phase_mappings.md", content)

    # ============================================================================
    # MERMAID DIAGRAM GENERATION
    # ============================================================================

    def generate_mermaid(self):
        """Generate Mermaid diagram files"""
        print("\n=== Generating Mermaid Diagrams ===\n")

        diagrams_dir = self.output_dir / "diagrams"

        # Phase state machine
        self._generate_phase_state_machine(diagrams_dir)

        # Workflow diagrams (5+ workflows)
        self._generate_workflow_diagrams(diagrams_dir)

        # Component interactions
        self._generate_component_interactions(diagrams_dir)

    def _generate_phase_state_machine(self, diagrams_dir: Path):
        """Generate phase state machine diagram"""
        mermaid = """# Phase State Machine

```mermaid
stateDiagram-v2
    [*] --> 1_BOOTSTRAP
    1_BOOTSTRAP --> 2_DISCOVERY
    2_DISCOVERY --> 3_DESIGN
    3_DESIGN --> 4_APPROVAL
    4_APPROVAL --> 5_REGISTRATION
    5_REGISTRATION --> 6_EXECUTION
    6_EXECUTION --> 7_CONSOLIDATION
    7_CONSOLIDATION --> 8_MAINTENANCE
    8_MAINTENANCE --> 9_SYNC_AND_FINALIZE
    9_SYNC_AND_FINALIZE --> [*]

    3_DESIGN --> 2_DISCOVERY : Need more info
    4_APPROVAL --> 3_DESIGN : Rejected
    6_EXECUTION --> 6_EXECUTION : Retry
```

## Phase Descriptions

"""
        for phase_id in self.universal_phases:
            phase_name = phase_id.replace('_', ' ').title()
            mermaid += f"- **{phase_name}**: {phase_id}\n"

        self._save_file(diagrams_dir / "phase_state_machine.md", mermaid)

    def _generate_workflow_diagrams(self, diagrams_dir: Path):
        """Generate workflow DAG diagrams"""
        workflows = self.index.get('by_workflow', {})

        for workflow_name, step_ids in workflows.items():
            steps = [s for s in self.steps if s.get('step_id') in step_ids]

            # Generate simple linear workflow for now
            mermaid = f"""# {workflow_name.replace('_', ' ').title()} Workflow

```mermaid
graph TD
"""
            for i, step in enumerate(steps[:20]):  # Limit to 20 for readability
                step_id = step.get('step_id', f'S{i}').replace('-', '_')
                name = step.get('name', 'Unknown')[:30]
                mermaid += f"    {step_id}[\"{name}\"]\n"
                if i > 0:
                    prev_step_id = steps[i-1].get('step_id', f'S{i-1}').replace('-', '_')
                    mermaid += f"    {prev_step_id} --> {step_id}\n"

            if len(steps) > 20:
                mermaid += f"    ... [{len(steps) - 20} more steps]\n"

            mermaid += "```\n"

            self._save_file(diagrams_dir / f"workflow_{workflow_name}.md", mermaid)

    def _generate_component_interactions(self, diagrams_dir: Path):
        """Generate component interaction diagram"""
        components = list(self.index.get('by_component', {}).keys())[:10]  # Top 10

        mermaid = """# Component Interactions

```mermaid
graph LR
"""
        for i, component in enumerate(components):
            comp_id = component.replace('::', '_').replace('-', '_')
            mermaid += f"    {comp_id}[{component}]\n"

        # Add some sample interactions (would be enhanced with actual dependency analysis)
        if len(components) >= 3:
            mermaid += f"    {components[0].replace('::', '_')} --> {components[1].replace('::', '_')}\n"
            mermaid += f"    {components[1].replace('::', '_')} --> {components[2].replace('::', '_')}\n"

        mermaid += "```\n"

        self._save_file(diagrams_dir / "component_interactions.md", mermaid)

    # ============================================================================
    # DRAWIO GENERATION
    # ============================================================================

    def generate_drawio(self):
        """Generate DrawIO XML files"""
        print("\n=== Generating DrawIO Files ===\n")

        drawio_dir = self.output_dir / "drawio"
        workflows = self.index.get('by_workflow', {})

        for workflow_name in list(workflows.keys())[:5]:  # Generate for first 5 workflows
            self._generate_drawio_workflow(drawio_dir, workflow_name)

    def _generate_drawio_workflow(self, drawio_dir: Path, workflow_name: str):
        """Generate DrawIO XML for a workflow"""
        # Simplified DrawIO XML structure
        xml = f"""<?xml version="1.0" encoding="UTF-8"?>
<mxfile host="app.diagrams.net" modified="2024-12-18T00:00:00.000Z">
  <diagram name="{workflow_name}" id="workflow_{workflow_name}">
    <mxGraphModel dx="1422" dy="794" grid="1" gridSize="10" guides="1">
      <root>
        <mxCell id="0"/>
        <mxCell id="1" parent="0"/>
        <!-- Workflow: {workflow_name} -->
        <mxCell id="start" value="Start" style="ellipse;whiteSpace=wrap;html=1;fillColor=#d5e8d4;" vertex="1" parent="1">
          <mxGeometry x="40" y="40" width="120" height="60" as="geometry"/>
        </mxCell>
        <mxCell id="end" value="End" style="ellipse;whiteSpace=wrap;html=1;fillColor=#f8cecc;" vertex="1" parent="1">
          <mxGeometry x="40" y="500" width="120" height="60" as="geometry"/>
        </mxCell>
        <mxCell id="arrow1" edge="1" parent="1" source="start" target="end">
          <mxGeometry relative="1" as="geometry"/>
        </mxCell>
      </root>
    </mxGraphModel>
  </diagram>
</mxfile>
"""
        self._save_file(drawio_dir / f"{workflow_name}.drawio", xml)

    # ============================================================================
    # HTML GENERATION
    # ============================================================================

    def generate_html(self):
        """Generate interactive HTML view"""
        print("\n=== Generating HTML Interactive View ===\n")

        html = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E2E Process Map - Interactive View</title>
    <script src="https://cdn.jsdelivr.net/npm/vue@3/dist/vue.global.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; }
        #app { display: flex; height: 100vh; }
        .sidebar { width: 300px; background: #f5f5f5; padding: 20px; overflow-y: auto; border-right: 1px solid #ddd; }
        .main { flex: 1; padding: 20px; overflow-y: auto; }
        h1 { font-size: 24px; margin-bottom: 20px; }
        h2 { font-size: 18px; margin: 20px 0 10px; }
        .search { width: 100%; padding: 10px; margin-bottom: 20px; border: 1px solid #ddd; border-radius: 4px; }
        .filter { margin-bottom: 15px; }
        .filter label { display: block; margin-bottom: 5px; font-weight: 600; }
        .filter select { width: 100%; padding: 8px; border: 1px solid #ddd; border-radius: 4px; }
        .step { background: white; border: 1px solid #ddd; border-radius: 4px; padding: 15px; margin-bottom: 10px; }
        .step-id { font-weight: 600; color: #0066cc; }
        .step-name { font-size: 16px; margin: 5px 0; }
        .step-meta { font-size: 12px; color: #666; }
        .badge { display: inline-block; padding: 2px 8px; border-radius: 3px; font-size: 11px; margin-right: 5px; }
        .badge-phase { background: #e3f2fd; color: #1976d2; }
        .badge-operation { background: #f3e5f5; color: #7b1fa2; }
    </style>
</head>
<body>
    <div id="app">
        <div class="sidebar">
            <h1>E2E Process Map</h1>
            <input type="text" v-model="searchQuery" class="search" placeholder="Search steps...">

            <div class="filter">
                <label>Phase</label>
                <select v-model="selectedPhase">
                    <option value="">All Phases</option>
                    <option v-for="phase in phases" :value="phase">{{ phase }}</option>
                </select>
            </div>

            <div class="filter">
                <label>Operation</label>
                <select v-model="selectedOperation">
                    <option value="">All Operations</option>
                    <option v-for="op in operations" :value="op">{{ op }}</option>
                </select>
            </div>

            <div class="filter">
                <label>Component</label>
                <select v-model="selectedComponent">
                    <option value="">All Components</option>
                    <option v-for="comp in components" :value="comp">{{ comp }}</option>
                </select>
            </div>

            <div style="margin-top: 20px; font-size: 12px; color: #666;">
                Showing {{ filteredSteps.length }} of {{ steps.length }} steps
            </div>
        </div>

        <div class="main">
            <h2>Process Steps</h2>
            <div v-for="step in paginatedSteps" :key="step.step_id" class="step">
                <div class="step-id">{{ step.step_id }}</div>
                <div class="step-name">{{ step.name }}</div>
                <div class="step-meta">
                    <span class="badge badge-phase">{{ step.universal_phase }}</span>
                    <span class="badge badge-operation">{{ step.operation_kind }}</span>
                </div>
                <div class="step-meta" style="margin-top: 5px;">
                    <strong>Component:</strong> {{ step.responsible_component }}
                </div>
            </div>

            <div v-if="filteredSteps.length > pageSize" style="margin-top: 20px; text-align: center;">
                <button @click="currentPage--" :disabled="currentPage === 1">Previous</button>
                <span style="margin: 0 10px;">Page {{ currentPage }} of {{ totalPages }}</span>
                <button @click="currentPage++" :disabled="currentPage === totalPages">Next</button>
            </div>
        </div>
    </div>

    <script>
        const { createApp } = Vue;

        createApp({
            data() {
                return {
                    steps: """ + json.dumps(self.steps[:100]) + """,
                    searchQuery: '',
                    selectedPhase: '',
                    selectedOperation: '',
                    selectedComponent: '',
                    currentPage: 1,
                    pageSize: 20
                }
            },
            computed: {
                phases() {
                    return [...new Set(this.steps.map(s => s.universal_phase))].sort();
                },
                operations() {
                    return [...new Set(this.steps.map(s => s.operation_kind))].sort();
                },
                components() {
                    return [...new Set(this.steps.map(s => s.responsible_component))].sort();
                },
                filteredSteps() {
                    return this.steps.filter(step => {
                        const matchSearch = !this.searchQuery ||
                            step.name.toLowerCase().includes(this.searchQuery.toLowerCase()) ||
                            step.step_id.toLowerCase().includes(this.searchQuery.toLowerCase());
                        const matchPhase = !this.selectedPhase || step.universal_phase === this.selectedPhase;
                        const matchOperation = !this.selectedOperation || step.operation_kind === this.selectedOperation;
                        const matchComponent = !this.selectedComponent || step.responsible_component === this.selectedComponent;
                        return matchSearch && matchPhase && matchOperation && matchComponent;
                    });
                },
                totalPages() {
                    return Math.ceil(this.filteredSteps.length / this.pageSize);
                },
                paginatedSteps() {
                    const start = (this.currentPage - 1) * this.pageSize;
                    return this.filteredSteps.slice(start, start + this.pageSize);
                }
            },
            watch: {
                filteredSteps() {
                    this.currentPage = 1;
                }
            }
        }).mount('#app');
    </script>
</body>
</html>
"""
        self._save_file(self.output_dir / "index.html", html)


def main():
    parser = argparse.ArgumentParser(description='Generate E2E process documentation')
    parser.add_argument('--schema', type=Path, required=True, help='Path to unified schema YAML')
    parser.add_argument('--index', type=Path, required=True, help='Path to master index JSON')
    parser.add_argument('--output-dir', type=Path, required=True, help='Output directory for documentation')
    parser.add_argument('--formats', nargs='+', choices=['markdown', 'mermaid', 'drawio', 'html'],
                       default=['markdown', 'mermaid', 'drawio', 'html'],
                       help='Formats to generate (default: all)')

    args = parser.parse_args()

    print("=" * 80)
    print("E2E DOCUMENTATION GENERATOR")
    print("=" * 80)
    print()

    # Validate inputs
    if not args.schema.exists():
        print(f"Error: Schema file not found: {args.schema}")
        sys.exit(1)

    if not args.index.exists():
        print(f"Error: Index file not found: {args.index}")
        sys.exit(1)

    # Create generator
    generator = E2EDocGenerator(args.schema, args.index, args.output_dir)

    # Generate requested formats
    if 'markdown' in args.formats:
        generator.generate_markdown()

    if 'mermaid' in args.formats:
        generator.generate_mermaid()

    if 'drawio' in args.formats:
        generator.generate_drawio()

    if 'html' in args.formats:
        generator.generate_html()

    print()
    print("=" * 80)
    print("DOCUMENTATION GENERATION COMPLETE")
    print("=" * 80)
    print(f"\nOutput directory: {args.output_dir}")
    print("\nGenerated documentation:")
    print("  - README.md (main index)")
    print(f"  - phases/ (9 phase guides)")
    print("  - workflows/ (workflow guides)")
    print("  - diagrams/ (Mermaid diagrams)")
    if 'drawio' in args.formats:
        print("  - drawio/ (DrawIO workflow files)")
    if 'html' in args.formats:
        print("  - index.html (interactive view)")
    print()


if __name__ == '__main__':
    main()
