# DOC_LINK: DOC-CONFIG-DIR-MANIFEST-RUNTIME-RUNS-1035
classification: runtime
dir_id: DIR-ALL_AI-RUNTIME-RUNS-2732269d
doc_id: DOC-CONFIG-DIR-MANIFEST-RUNTIME-RUNS-1035
files:
  documentation:
  - README.md
  metadata:
  - DIR_MANIFEST.yaml
  - .dir_id
  registries:
  - RUN_REGISTRY.yaml
meta: {}
ownership:
  created: '2026-01-04T01:29:06.265219Z'
  owner: Execution Engine
  status: active
purpose: Registry for Run Identifier (run_id)
version: 1.0.0
